# Generated by Django 4.1.7 on 2023-03-31 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('phonenumber', models.CharField(max_length=50, null=True)),
                ('passportnumber', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_country', models.CharField(max_length=50, null=True)),
                ('price_place', models.IntegerField()),
                ('statue', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(choices=[('2 beds', '2 beds'), ('3 beds', '3 beds'), ('4 beds', '4 beds')], max_length=50, null=True, unique=True)),
                ('price', models.IntegerField()),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.place')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(null=True)),
                ('date_fin', models.DateField(null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.client')),
                ('voyage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.voyage')),
            ],
        ),
    ]
