# Generated by Django 4.1.7 on 2023-03-31 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_voyage_place_order_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='voyage',
            name='room',
        ),
        migrations.AlterField(
            model_name='place',
            name='price_place',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='voyage',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='voyage',
            name='Category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.chambre'),
        ),
    ]
