# Generated by Django 4.1.7 on 2023-03-31 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_chambre_remove_voyage_room_alter_place_price_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.RemoveField(
            model_name='order',
            name='place',
        ),
        migrations.RemoveField(
            model_name='order',
            name='voyage',
        ),
        migrations.RemoveField(
            model_name='voyage',
            name='Category',
        ),
        migrations.DeleteModel(
            name='chambre',
        ),
        migrations.DeleteModel(
            name='order',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='voyage',
        ),
    ]
