# Generated by Django 4.1.7 on 2023-03-31 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_remove_order_client_remove_order_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_country', models.CharField(max_length=50, null=True)),
                ('price_place', models.FloatField()),
                ('statue', models.CharField(choices=[('Available', 'Available'), ('Not Available', 'Not Available')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='voyage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('Category', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.chambre')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(null=True)),
                ('date_fin', models.DateField(null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.client')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.place')),
                ('voyage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.voyage')),
            ],
        ),
    ]
