# Generated by Django 4.1.7 on 2023-03-31 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_chambre_place_voyage_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyage',
            name='Category',
        ),
        migrations.AddField(
            model_name='voyage',
            name='room',
            field=models.CharField(choices=[('2 beds', '2 beds'), ('3 beds', '3 beds'), ('4 beds', '4 beds')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='chambre',
        ),
    ]
