# Generated by Django 4.1.7 on 2023-04-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_remove_voyage_category_voyage_room_delete_chambre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
