# Generated by Django 4.1.7 on 2023-04-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_alter_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='place_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
